"""Create files table

Revision ID: 6fe4a9a662d6
Revises: fdca6e5aea8d
Create Date: 2025-06-07 10:57:43.843712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe4a9a662d6'
down_revision: Union[str, None] = 'fdca6e5aea8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
