"""Add reference id in files

Revision ID: 87eaab091726
Revises: daee26c40595
Create Date: 2025-06-08 22:11:54.490677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87eaab091726'
down_revision: Union[str, None] = 'daee26c40595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('reference_document_ids', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'reference_document_ids')
    # ### end Alembic commands ###
