"""Create user files table

Revision ID: db20ab87daa8
Revises: 6fe4a9a662d6
Create Date: 2025-06-07 12:00:45.163488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db20ab87daa8'
down_revision: Union[str, None] = '6fe4a9a662d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_files_file_id'), 'user_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_user_files_id'), 'user_files', ['id'], unique=False)
    op.create_index(op.f('ix_user_files_user_id'), 'user_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_files_user_id'), table_name='user_files')
    op.drop_index(op.f('ix_user_files_id'), table_name='user_files')
    op.drop_index(op.f('ix_user_files_file_id'), table_name='user_files')
    op.drop_table('user_files')
    # ### end Alembic commands ###
